version: '3.8'
name: 'ts-homepage'
services:
  apache:
    container_name: 'apache'
    image: 'httpd:latest'
    command: >
      sh -c "apt-get update && apt-get install -y php libapache2-mod-php && apachectl -D FOREGROUND"
    ports:
      - '80:80'
    volumes:
      - ../www:/usr/local/apache2/htdocs/
      # - ./httpd.conf:/usr/local/apache2/conf/httpd.conf